### ISSUE TITLE
S1 clear zone on surf_sandman_v2 is misplaced

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#1]
**Describe the bug**
The zone that your character needs to enter to show having cleared S1 on the map surf_sandman_v2 is incorrect.
It should cover more of the spawn area for S2, but it currently only marks a clear if you touch the back wall.

**To Reproduce**
Go to S2 and try to get S1 completion.

**Screenshots**
https://i.imgur.com/TMPBcXb.png

**Comment by TeddiO** [comment]
Resolved when the server next changes to Sandman
