### ISSUE TITLE
Add autohop zone for surf_pandemonium on S5

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#10]
Please to add surf_pandemonium s5 autohop zones

https://i.imgur.com/Dy5sZYI.png

thank

**Comment by TeddiO** [comment]
That section isn't designed for a hop zone from what I can tell given the water that was placed there. It's possible to add one but it might require some further input before we potentially add one'.

**Comment by dwarfmagic** [comment]
After speaking with Staplee, jr, and juntko about whether there should be an autohop
There definitely should be

**Comment by Demonic748** [comment]
The water is too shallow to hold space in like stage 1, to complete it you have to scrollhop on the platform where the water is and slide off the bump.

**Comment by TeddiO** [comment]
So I did testing with this to see how consistent I could manoeuvre it without an ahop zone. While I could get it most of the time I did find that there were times I expected it to work and it just didn't so fair play, I'll add an ahop zone here to make it consistent.
