### ISSUE TITLE
Update Splits (in chat) for a few features

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#12]
**Is your feature request related to a problem? Please describe.**
When I am partway through a run, I can glance at the split and see two things:
1. The split time relative to my PB split. This is good and provides exactly enough information.
2. The overall time relative to my PB overall. This is OK, but is only colored green/red, and is not granular enough.
This is worse in the chat output of the splits, because overall time is not mentioned at ALL in the chat.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
What I would prefer to see is:
A) On the split popup, an overall +/- difference to see my current run time versus my PB run time.
    This would compare the time I currently have (69s at split 5) to my PB (65s at split 5) and show +4s on the overall time.
B) On the chat output, an overall indicator (to show what my current overall time is, recorded to chat) as well as the difference.
    This would continue to display the current split with existing format, but also some mention of overall time at that split.

**Additional context**
Current Split Display: https://i.imgur.com/3ZptAVu.png
Proposed Split Display: https://i.imgur.com/mrzrhlC.png
Current Split Chat: https://i.imgur.com/HlztgJA.png
Proposed Split Chat: https://i.imgur.com/Mlmkza2.png

Additionally, a feature that outputs a completed run's times all as one table/output into console (NOT CHAT) would be welcome on staged maps.

**Comment by TeddiO** [comment]
Updates relating to this request will be going live within the next hour or so. The split display remains unchanged as that's intended for "at a glance" and more suited for introductory players. Chat splits however now contain the full breadth of information requested alongside the ability to change `surf_output_split_console` to `1` (or change it in F1) which will output splits to console afterwards.
