### ISSUE TITLE
surf_guitar_hi completion achievement bug

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#14]
**Describe the bug**
The map completion achievement for surf_guitar_hi on the hard server is still categorized under Surf - Easy > Map Completion instead of Surf - Hard > Map Completion.

**Corresponding lauerror**
N/A

**To Reproduce**
1. Connect a [BB] surf server
2. Press F1 and navigate to the Achievements tab
3. Click on the "Surf - Easy" achievement category
4. Click on "Map Completion" category under "Surf-Easy"
5. Navigate through all the achievements until you locate the surf_guitar_hi achievement (unlocked or not)

**Screenshots**
![image](https://i.imgur.com/oCl1932.png)
*surf_guitar_hi achievement next to surf-easy achievements*

**Desktop (please complete the following information):**
 - OS: Windows
 - Binary Version: 64-bit

**Additional context**
You will not receive the map completion achievement when completing surf_guitar_hi on the hard surf server. (assuming this is because of the reason above)

**Comment by TeddiO** [comment]
So looking in to this, it looks mostly like the achievement is just mis-categorized and as such that particular achievement should be in the hard section. The original easy achievement was called `Strumming The Guitar`, though you won't be able to see this one if you didn't earn it back in the day. There is a secondary issue where it might actually be possible to earn the old achievement so I'll fix that at the same time.

**Comment by TeddiO** [comment]
Pushed the fix live now
