### ISSUE TITLE
surf_squirrelsonvacation fps drop

### ISSUE THREAD

**Issue by Demonic748** [BB-Games/gamemode-issues-requests#16]
The pee stream at the start of the map seems to cause a large drop in frame rate that's annoying to deal with while going for runs. I'm not sure if it's actually the stream that's causing it, but the low fps only occurs [near the first ramp](https://imgur.com/pZn6umh).

If it is indeed the problem, i was wondering if it would be possible to freeze the texture or replace it, similar to what has been done for other maps with animated textures, and hopefully that would resolve the issue.

**Comment by TeddiO** [comment]
It's not the "pee" which causes this, I think it's the fact you're able to look over the entire map and effectively have it rendered until you dip in to the canyon. To try and give an example of this occuring, the below screenshots should show you what happens without material texture "blocking" your line of sight - 

- https://teddi.eu/ss/13a52fa1-a852-4dc3-888b-b6f832c55557n-TanEthiopianwolf.png
- https://teddi.eu/ss/f1c47bf4-6644-458f-87b1-8b3c7a9c2056n-HumblePig.png

There's zero culling in effect and so you're rendering the entire world _and_ every player in it. Once you dip in to the canyon however:

- https://teddi.eu/ss/93ebaf04-3104-473e-9e47-f9bc0eb5804dn-PettyPekingese.png
- https://teddi.eu/ss/6ec40466-74ac-49a3-801d-ca83d463fe9bn-PalevioletredCrossbill.png

If you stand here ( https://teddi.eu/ss/eeab5d4b-09ae-41b1-85a9-99d0b93db9ean-BreakableArawana.png ) then you'll notice you can watch the stream with no frame drops.

It's still not perfect and the map could **absolutely** be better, but I'm not aware of any way using GLua to provide any form of culling that isn't effectively slicing up part of the world (and even then, that might not work). I guess the key question is do we want to keep the map? It doesn't have LDR support and with the performance it supplies it might not be worth keeping

**Comment by TeddiO** [comment]
For the time being I'm unable to find a reasonable way to do this, so I'll close this until something changes.
