### ISSUE TITLE
Enable Streamer Keyboard Setting + Spectating & Unspectating Makes the Streamer Keyboard Disappear

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#18]
**Describe the bug**
If you have the enable streamer keyboard setting checked, you should see the streamer keyboard at all times. However, if you spectate a player on a surf server then unspectate said player, the streamer keyboard disappears regardless if you have the setting option checked. 

**Corresponding lauerror**
N/A

**To Reproduce**
1. Connect to any [BB] Surf Server 
2. Press F1 > Settings > General > Enable Streamer Keyboard (Make sure this is checked)
3. /spectate another player that is connected on the server
4. /unspec the player you were spectating
5. Notice how the streamer keyboard disappears and will not show until you reconnect or recheck the setting option

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Binary Version: 64-bit

**Additional context**
I really couldn't think of a shorter title. :)

**Comment by TeddiO** [comment]
It's bit of a low priority one as there's a known "fixable" workaround and I'm not entirely sure how many people actually use this

**Comment by TeddiO** [comment]
This fix should be live fairly soon.
