### ISSUE TITLE
Add Autohop to S4 in surf_happyhug

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#2]
**Is your feature request related to a problem? Please describe.**
I can't bhop for shit and I need assistance on S4 where the map got sushi rolls

**Why you would like to see this resolved, what does it enhance / bring to the table?**
I wouldn't have to rely on my poor bhop mechanics to play surf

**Additional context**
https://i.imgur.com/4QuA73n.png

**Comment by TeddiO** [comment]
Added, however due to how the brushwork is done on that map it seems there's some odd z-fighting that pops up with the viewing of the zone / bunny image. As a result I've elevated the zone as a whole so you'll still get the whole "hold space to hop" message pop up.
