### ISSUE TITLE
"No Viagra Required!" Hard maps completion needs updating

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#22]
The current map list for "Complete all the hard server maps."/"No Viagra Required!" achievement is out-of-date.
https://i.imgur.com/huZpv8e.png

**Comment by TeddiO** [comment]
Is it out of date in terms of maps removed or rather you'd like to see new maps added? We don't often update meta achievements unless it's to remove maps that can no longer be attained.

**Comment by dwarfmagic** [comment]
All of these maps are possible, it's just out of date in terms of which maps are available on the hard server.
For example, I don't think you need to beat tronic to get this achievement, while it's available on the hard server.
