### ISSUE TITLE
Add "Holiday Items" as a Filter Option in Inventory

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#24]
**Is your feature request related to a problem? Please describe.**
I found myself looking for a specific Halloween item I didn't know the name of through my 800+ items inside my inventory. I was looking for a specific Halloween item to discover which slot it would cover in cosmetic items and was ultimately unable to find it and gave up until I received it in a crate again.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Being able to filter through Holiday Items would be very helpful to eliminate the time it'd take to look through every single item inside your large inventory if you're clueless to the name or slot the item uses during the holiday seasons (and save our eyes. :D)

**Additional context**
Happy Halloween 🎃

**Comment by TeddiO** [comment]
Strictly speaking the database has no concept of holiday items, the restrictions are actually added based on the item schemas. It *probably* wouldn't be too much effort to add such support, but I'll leave it up to @killermon to decide if he wants to commit resource to this.

**Comment by killermon** [comment]
It's technically possible with the current systems (Although it requires a minor fix on how categories work, as they're meant to be bitwise but we don't use them like that).

My concerns mostly sit in the camp of we have a lot of filters already for new players and I don't want to make a filter for every permutation.

We do also have the ability to sort your inventory by when the item was received, which will bring any new items to the top.

**Comment by killermon** [comment]
I think this can be closed now as no further discussion

**Comment by killermon** [comment]
So I can't close this, @TeddiO
