### ISSUE TITLE
Remove Obnoxious Ambient Noises from Surf_Nyx

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#27]
**Is your feature request related to a problem? Please describe.**
The ambient noise in surf_nyx is loud, and obnoxious. It's difficult to surf and listen to my sick tunes while hearing loud water droplets and obnoxious DINGS, especially while having the game open in the background to continue moderating voice, I have to sit and listen to the obnoxious ambient noises for 30 minutes. Some have recommended to stop sounds in console however, most of the ambient noises are replayed shortly after and have no affect on stopping the noises.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
I'm not the only one that has complained about the ambient noises on nyx. This would be something most players (and staff) would love to see. Especially ones that listen to music and or are communicating with their friends over an external VOIP application or in-game while surfing.

**Additional context**
I did it Teddi.

**Comment by TeddiO** [comment]
Do you happen to have the audio paths? It's okay if you don't - just helps speed things up!

**Comment by TeddiO** [comment]
Seeing a we happened to be on the map, I ran a soundlist report and I think these are likely the offending sounds - 

```L( 2b) 422276 : ambient\atmosphere\tone_alley.wav
 ( 2b)  70654 : ambient\wind\wind_snippet2.wav
 ( 2b)  95532 : ambient\wind\smallgust.wav
 ( 2b) 131070 : ambient\wind\wind_snippet1.wav
 ( 2b) 120320 : ambient\misc\metal2.wav
L( 2b) 201908 : ambient\levels\canals\toxic_slime_loop1.wav
 ( 2b)  78202 : ambient\levels\canals\windchime2.wav
 ( 2b)  46092 : ambient\levels\canals\windchime5.wav
 ( 2b) 376914 : ambient\levels\canals\windchine1.wav
 ( 2b)  26488 : ambient\weather\drip3.wav
 ( 2b)  27340 : ambient\weather\drip1.wav
 ( 2b)  34566 : ambient\weather\drip2.wav
 ( 2b)  29594 : ambient\weather\drip4.wav
 ( 2b) 493920 : ambient\nature\wind_leaves_mild_gust_1.wav
```

**Comment by ChacoEleven** [comment]
Those are most definitely the audio files used.

I can still hear those wind chimes and drips in my head.
