### ISSUE TITLE
Auto Scroll Chat Option

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#29]
**Is your feature request related to a problem? Please describe.**
I've encountered multiple instances where I've looked through previous message in the chat box and have a habit of pressing ESC in that spot while in the chat box instead of scrolling down then pressing ESC resulting in chat getting stuck in that area you were at and future messages sent into the chat box will not be seen until you manually scroll down. This is incredibly annoying when attempting a PB run with timetrial splits chat outputs enabled only to find out, you can't see it resulting in ending your run to manually scroll down.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
I'd like to see an option added that gives users the choice to have the chat box auto scroll to new messages. This would be certainly helpful for myself as a sub-admin and helpful to other users who output timetrial splits to chat.

**Additional context**
N/A

**Comment by TeddiO** [comment]
To clarify when you say scroll to new messages, you mean moment there's a new message that it jumps down?

If so that's pretty straightforwards to implement (and at one point I think was the behaviour)

**Comment by ChacoEleven** [comment]
> To clarify when you say scroll to new messages, you mean moment there's a new message that it jumps down?

Yes, that is what I mean. :D

**Comment by TeddiO** [comment]
This should be live as of the next changelevel on all servers.
