### ISSUE TITLE
respawn and !r for surf_frequency_no_jail doesn't reset time

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#3]
**Describe the bug**
When respawning via failing the map, or by using !r, the surf timer is not reset.

**To Reproduce**
Go on surf_frequency_no_jail, start the map
Upon dying, your time will not reset to 0, but will keep incrementing as if no restart occurred
Upon using !r, your time will freeze, not reset, and will not increment upon starting the level

**Screenshots**
Respawn point: https://i.imgur.com/ohfDfW1.png
Existing timer: https://i.imgur.com/qyHKMbl.png

**Additional context**
Dude my flow is totally ruined by this janky timer box bro
how am I supposed to get in the groove of repeatedly failing a map if my timer is out of sync

**Comment by TeddiO** [comment]
Added
