### ISSUE TITLE
Add autohop to surf_tendies Bonus 2

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#30]
**Is your feature request related to a problem? Please describe.**
Lemme get that uhhhhhhhhhh server hopping for me please

**Why you would like to see this resolved, what does it enhance / bring to the table?**
I cannae scroll fast enough

**Additional context**
https://i.imgur.com/agAVlFl.png

**Comment by TeddiO** [comment]
Added with the next update
