### ISSUE TITLE
Autohop zones on surf_kitsune2

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#32]
**Is your feature request related to a problem? Please describe.**
Ayy lemme get some boingo on kitsune2 so i can lay down ez clap times on tangerine and orange

**Why you would like to see this resolved, what does it enhance / bring to the table?**
the ramps are hard to hit and not always the best route, similar to ACE

**Additional context**
somethink like 3-4 hops is probably fine, just on the stage transitions, none of the actual stages should need any zones

**Comment by TeddiO** [comment]
I'm currently querying the mapping committee on their thoughts on a few solutions to this and if step-ahop is even wanted.

**Comment by TeddiO** [comment]
Step-ahop for kitsune2 will go live once the current surf season has closed.
