### ISSUE TITLE
Add autohop zone on surf_frequency_no_jail

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#33]
**Is your feature request related to a problem? Please describe.**
There's a circular column to hop on a bit of the ways through the map.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Lets me do the cool boing thing where I look like a pro player

**Additional context**
https://i.imgur.com/wvwHk08.png

**Comment by TeddiO** [comment]
Instead of an ahop zone I've added a step-ahop zone instead. Functionally this will work as per usual, it just uses the system that ace, aser, progress et all uses so there won't be any floating bunny but instead the notification you have an ahop step to use.
