### ISSUE TITLE
Display Current Map At Top of Window When Comparing Against Rivals/Challengers

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#36]
**Is your feature request related to a problem? Please describe.**
With the recent wonderful addition of Challengers and Rivals within the ranking system, I've noticed that if you do decide to compare times with either a challenger/rival, you have to scroll through each point of data to find the current map (which most people will use this feature for) loosing time to improve your time trial.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Most people will use this new feature to check the time trials of their rivals/challengers for the current map they're on compared to viewing their time trials for a specific map that is different from the current map. This would resolve the issue of having to take the time to scroll through the lengthy list of maps just to find data for the current map and allowing for more time of attempting to improve.

**Additional context**
N/A

**Comment by killermon** [comment]
Done for both the map times window, as well as the challengers and rivals windows

![image](https://i.imgur.com/krOdI6i.png)

![image](https://i.imgur.com/lQnuX7S.png)
