### ISSUE TITLE
Add AHop Zone to Stage 3 on surf_misc

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#38]
**Is your feature request related to a problem? Please describe.**
I once have seen many people stuck on stage 3 of surf_misc due to the fact that you are required to bhop on this platform in order to keep your speed and complete the stage. This is a huge bottleneck in the maps completion rate as there are multiple players that attempt to complete this map but are unable to as they lack the skill needed to pass the bhopping platform successfully.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Read above.

**Additional context**
Picture of the platform in question:
![image](https://user-images.githubusercontent.com/65062032/114256499-9e46b200-9987-11eb-8b68-b41988eac261.png)

**Comment by TeddiO** [comment]
This should be live once this issue is closed.
