### ISSUE TITLE
[surf] Toggle to enable centered speedometer

### ISSUE THREAD

**Issue by scherfj1** [BB-Games/gamemode-issues-requests#39]
something similar to this
https://www.youtube.com/watch?v=0vh2a_ILQCk&t=2s

**Comment by TeddiO** [comment]
Would the ability to set co-ordinates / possibly be able to drag the box about be better than a straight up toggle @scherfj1 ?

**Comment by scherfj1** [comment]
@TeddiO 

I can expand on the underlying motivations:

1. My screen is too large, meaning the box is far from the center of the screen. I can't see my speed without looking away from where my character is traveling to.
2. The speed value is too small, I can't determine changes in the speed as they happen without staring at it. (Meaning I'm not paying attention to character direction)
3. I want to be able to tell how turn rate / strafing is affecting my speed instantaneously. The video shows an example solution by changing the color of the speed value based on whether the value is increasing or decreasing. 

(1) & (2) are simpler and likely a greater QOL fix than (3), but (3) would be _amazing_ to have if (1) & (2) are added.

**Comment by TeddiO** [comment]
Oh I understand the motivations! It's more just would you like the ability to customise the exact location or do you prefer the idea of a straight up "center speedometer" checkbox

**Comment by scherfj1** [comment]
Being able to move it would be nice, sure.

**Comment by TeddiO** [comment]
This will be going live in the next hour or so across both servers. Players will be able to edit all of the Surf HUD elements (with the exception of stage selection) via the F1 menu.
