### ISSUE TITLE
Don't count AFK players in RTV/Extend votes required

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#4]
**Is your feature request related to a problem? Please describe.**
I have noticed on the hard surf server, there are usually not that many players online.
Meaning, that with a select few active players, there's no way to RTV while that player is still connected.
The same goes for extending a map, though I haven't specifically noticed when voting for that while AFK players are connected.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
This would strike a happy balance of keeping player counts high by not kicking via AFK,
while also not reducing the enjoyment of the players actually playing the game

**Comment by TeddiO** [comment]
AFK players are already ignored in extend and RTV votes. A player is deemed to be AFK if they've gone 5 minutes without touching their keyboard / mouse, so if a server has just changed level it'll take 5 minutes for them to be re-flagged as AFK.
