### ISSUE TITLE
surf_salvation configured with incorrect maxvel (3.5k -> 4k)

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#40]
**Describe the bug**
The current sv_maxvelocity on surf_salvation is set to 3500. It should be configured to 4000.

**Additional context**
Both original uploads for both versions (CSS/CSGO) of this map include configuring maxvel to 4k.
https://gamebanana.com/mods/82216
https://gamebanana.com/mods/137890
Literally nobody has cleared this map for months

**Comment by TeddiO** [comment]
Should be resolved once this issue is closed.
