### ISSUE TITLE
Bonus 1 Spawn Point on surf_fornax is Set Too Low

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#44]
**Describe the bug**
The spawn point position on bonus 1 of surf_fornax is set too low resulting in players getting stuck when entering the bonus stage requiring players to crouch to become released.

**Corresponding lua error**
*N/A*

**How to reproduce the issue**
1. Complete surf_fornax
2. Enter the 1st bonus stage with !b 1
3. Observe how the player is stuck and cannot move until they crouch

**Screenshots**
*N/A*

**System Information:**
*N/A*

**Additional context**
Reported by a player that was unable to move until notified to crouch.

**Comment by TeddiO** [comment]
When this issue is closed, the issue is resolved 😁
