### ISSUE TITLE
Unusuals not Showing on Self

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#49]
It seems an issue has started where you can't see some unusual effects on yourself in 3rd person. Other players when looking at you can see them. I think this'll cause some confusion for players and appreciate they're rare/expensive items that ideally they'd be able to see on themselves.

Can see this occurs with both Flaming and Plasma unusual, where if you wear a hat/mask with the effect they don't appear. Asteroid as well. Quite a few seem to work as normal and can be seen so it's odd.

**Comment by TeddiO** [comment]
Will bump this for @killermon

**Comment by TeddiO** [comment]
There were some changes made to the rendering system not that long ago, do we have confirmation this is still happening?

**Comment by bbkaiden** [comment]
Aye this is a still a problem - can see Flaming effect on a hat in Preview pane of the Equip tab, but not in 3rd person for example.

**Comment by TeddiO** [comment]
Updating this with new information: Confirmed it's not related to our systems directly and is a wider issue within GMod at the very least.

**Comment by Sod-ers** [comment]
Planetary effect is also affected by this bug. So if a solution is found, please apply it to Planetary too.

**Comment by TeddiO** [comment]
Found the issue, will apply the fix to 

- Planetary
- Flaming
- Plasma

Once this issue is closed and new ones are found, please open new issues. While this ticket remains open, feel free to add any others that aren't working.

**Comment by Sod-ers** [comment]
Please apply to Asteroid effect too.
