### ISSUE TITLE
surf_simpsons_source S3 booster is hot garbage

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#5]
**Describe the bug**
The boost hits one of three states seemingly at random: hecka boosted, normal boost which is barely enough, and literally no boost.

**To Reproduce**
Try to get a time on surf_simpsons_source
Do S3 at least a few times
Wonder why the booster has boosted different amounts each time, especially when other boosters on the map are much more consistent.

**Screenshots**
https://i.imgur.com/lQYkHeK.png

**Comment by TeddiO** [comment]
So I took a look at this and there's nothing immediately that sticks out as something being wrong other than the brush possibly being misplaced (https://teddi.eu/ss/ebd01a8e-53ea-4c14-a56a-53a2d50c18d2n-ArcticNilgai.png). This could be the result of the decompiler although this could be verified. The only thing is that simpsons_source is absolutely garbage in terms of a map and I'm reluctant to do any work on it.
