### ISSUE TITLE
Achivement Icons Bugged

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#52]
Achievement icons have been bugged last few days, I think since new ones were added to climb or when CYM aura icon was updated or so.

![image](https://user-images.githubusercontent.com/4204891/152620054-561d644b-5615-46f8-ac57-defa20cf4954.png)

**Comment by TeddiO** [comment]
Not entirely sure what's happened here, looks like workshop addon may have bugged out for unknown reasons.

**Comment by TeddiO** [comment]
So it looks like there's two issues at play here, once is that prefixed `/` on a material path is no longer seen as valid, the other is it appears we use `error.png` when we don't have an image but that path no longer exists.

**Comment by TeddiO** [comment]
Looks like `error.png` is mapped to another achievement which has the `/` prefix issue, so updated that and we seem to be back on the right track.

**Comment by TeddiO** [comment]
Update has been deployed to resolve this!
