### ISSUE TITLE
Console Spam Sprites

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#53]
Been going on for a while but I get constant spam in the console around unusual effects or similar. At times it can spam for the entire map. Sometime I don't see it at all though.

C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_invasion_boogaloop"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_constellations_purple"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_invasion_boogaloop"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_constellations_purple"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_invasion_boogaloop"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_constellations_purple"!
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "unusual_invasion_boogaloop"! (x69)

**Comment by TeddiO** [comment]
This looks to be resolved now.
