### ISSUE TITLE
Remove “/unspectate” text from the streamer keyboard

### ISSUE THREAD

**Issue by BBSoders** [BB-Games/gamemode-issues-requests#55]
**Describe the bug**
When the streamer keyboard is enabled, it always shows the “Type /unspectate to stop spectating.” hint text, regardless of being the active player.

**Corresponding lua error**
N/A

**How to reproduce the issue**
Press F1 > Settings > Gamemode Settings > Enable Streamer Keyboard

**Screenshots**
https://i.imgur.com/oKDM2hQ.png

**System Information:**
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

**Additional context**
I am recording a lot of surf gameplay and I want to publish it, but all of my content looks like I’m spectating due to that hint text; fixing this would clear any confusion a viewer might have.

**Comment by TeddiO** [comment]
When this issue is closed, within an hour this should be available.
