### ISSUE TITLE
New Item Shogun Kunai Issue

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#58]
New item should be a dagger in each hand, at present it's just one. It should be a combination of both of the below. If both Items exist in the tables they should be merged into one item and called just 'Shogun Kunai'.

-- Shogun Kunai_1
BB.EquipableItemData[<ID>] = {
	Slost = ITEM_EQUIP_SLOT_ARMS,
	Models = {
		{ Model = "models/workshop_partner/weapons/c_models/c_shogun_kunai/c_shogun_kunai.mdl", Bone = "ValveBiped.Bip01_R_Hand", Scale = 1, AngleOffset = Angle(-1.319,-0.329,-166.921), PosOffset=Vector(3.554,-1.576,0.616)},
	},
}
-- Shogun Kunai_2
BB.EquipableItemData[<ID>] = {
	Slost = ITEM_EQUIP_SLOT_ARMS,
	Models = {
		{ Model = "models/workshop_partner/weapons/c_models/c_shogun_kunai/c_shogun_kunai.mdl", Bone = "ValveBiped.Bip01_L_Hand", Scale = 1, AngleOffset = Angle(-1.319,-0.329,-26.074), PosOffset=Vector(4.516,-1.581,0.638)},
	},
}

**Comment by TeddiO** [comment]
Given the item is in the wild, it's a little trickier to resolve this (but not impossible).

What could be interesting, although I don't know how much players would enjoy this is if we made a new crafting recipe that allowed players to combine them into one item. Gives more substance to the item system and gives players choice as well

**Comment by killermon** [comment]
This was fixed the other night, did it before any got out into the wild
