### ISSUE TITLE
Update Nuclear Ending

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#59]
Can we update the Surf_Nuclear ending - the videos I watched all use a skip which makes it look a lot harder than it is, which is why the zone was brought forward.

If we can update the end zone to start at the top of this pillar and reach across the whole cylinder shape should work.

![image](https://user-images.githubusercontent.com/4204891/208244436-e82dfa37-2f2e-4961-9e1a-2df7815e3eea.png)

**Comment by TeddiO** [comment]
Change will go live on 1st of July which changes this ending.
