### ISSUE TITLE
add command for surf_reset_stage

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#6]
**Is your feature request related to a problem? Please describe.**
I want to restart the current stage I'm on, whether that's to show someone how to do a level, or practicing a skip.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
The advantage of this command would be to be able to reset the current stage without needing to rebind a "say /s #" for each time a different stage is encountered.

**Additional context**
Since the current stage is already tracked, this should be a relatively simple command to add, and could likely hook into the coding for the /s # command anyhow.

**Comment by TeddiO** [comment]
This is live as of the next time the maps change level. It's worth mentioning that while it resets your position, it doesn't reset eye angles so you may find you're looking away from the stage when you get respawned.
