### ISSUE TITLE
surf_agony Booster RNG

### ISSUE THREAD

**Issue by NeffyPlus** [BB-Games/gamemode-issues-requests#60]
**Describe the bug**
the booster on map surf_agony is randomized due to inability to hop at the exact moment of landing

**Corresponding lua error**
n/a

**How to reproduce the issue**
unable to reproduce but a ahop zone might fix it

Sometimes issues can happen out of the blue. That's okay! As long as you give a rough idea of what you were doing at the time.
-->

**Comment by TeddiO** [comment]
After some investigation, hopping won't make a difference to this unfortunately as the player never "steps" on the booster.
