### ISSUE TITLE
/admin Bug Report Suggestion & Self Reporting

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#62]
Please can reporting a bug on /admin advise the user to visit Discord and not @ Discord? It's often not warranted @'ing 21 people with 'I found a bug!' with no context, and they usually just need guidance on something which people can provide on General.

On the same topic, please can selecting yourself on the /admin list whilst making a report either block the report or something else - these also don't need to @ 21 people.

**Comment by TeddiO** [comment]
When this issue is closed, updates should be live on each server within an hour.
