### ISSUE TITLE
Add Random Button to Vote Map

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#63]
In the interest of having it's own thread, please can we add a Random button to the Votemap screen? Up to you how this is implemented, it could visibly cast your vote in the last second or so, or just add everyone's random votes to a random map at the end of calculation.

I expect the button would appear above all the others.

**Comment by TeddiO** [comment]
What I think I'd do with random map is if it won, it'd literally just land on a random map that's available.

**Comment by bbkaiden** [comment]
Yeah works for me! Guess everyone voting random needs to pool their votes together then select that. Is the intention for it to instantly select a random map? Just wondering if needs to lock in or not show the choice or something, otherwise players can just change their mind which seems a bit moot. If 5 people choose random and it places all their votes on different maps they're never going to win so won't see any use I think.

**Comment by TeddiO** [comment]
When this issue is closed, some code has been merged to facilitate this request.
