### ISSUE TITLE
Change how maps order on Vote Map

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#64]
Maps should appear on the vote map screen in a random order - right now the same maps like 4head and Squirrels often appear at the very top, which sees them disproportionally voted vs maps that seem to always appear at the bottom. This doesn't help when maps like 4Head and Squirrels tend to empty the server more than say Boreas which sees less votes.

I'm not sure how it's sorting right now, but it's definitely not random which would be a much better system.

**Comment by TeddiO** [comment]
As the client can dictate this and players may not like the change, what about if it was configuration?

So by default it could be random sorted, but it could be configured to be ascending / descending.

**Comment by bbkaiden** [comment]
Yeah is fine by me, would say most will be happy with random default as they can pin their favs, but a choice to sort either on the vote screen or in F1 > settings would be fine.

**Comment by bbkaiden** [comment]
Just guessing everyone needs to see the same random if it is random every time, given the scroll bar?

**Comment by bbkaiden** [comment]
Mostly sorted by new random button.

**Comment by bbkaiden** [comment]
close
