### ISSUE TITLE
Whiteout 5-6 stage Autohop

### ISSUE THREAD

**Issue by BearFromBB** [BB-Games/gamemode-issues-requests#67]
**spot between stage 5-6 autohop "tends to not trigger on the left side"
do not know how to recreate said issue.

```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 11:22:35 Oct 31 2023 (9033) (4000)
GMod version 2023.10.31, branch: x86-64, multicore: 1
Windows 64bit
```

just a reminder for later.

**Comment by TeddiO** [comment]
Once this issue is closed, a fix has been merged and should be live within the next few hours.
