### ISSUE TITLE
Bazaar: Bypass Minimum Bid Restrictions to Recycle Rejected Bids

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#69]
**Describe the bug**
Found a repeatable condition to bid below the price of my previous bid. It's possible to obtain all currency achievements using this method because each rejected bid counts as cubes earned. Only applicable to the Bazaar, this behavior doesn't work backwards with the Player Marketplace.

**How to reproduce the issue**

    1. Open Player Marketplace & load a listing category.
    2. Open The Bazaar. Bid on an item (or select no) and quickly (before loading finishes) click the Player Marketplace and select a different category.
    3. When the Bazaar listings show in the Player Marketplace, the next bid placed will always appear to you as the minimum bid.

**Screenshots**
![1](https://github.com/user-attachments/assets/8634d5b6-e27f-44b7-9829-0dd29f0432d2)
![2](https://github.com/user-attachments/assets/5780fda3-27fb-43bb-be5b-8f06c19c129d)

**System Information:**
```Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:23:57 Jul 12 2024 (9379) (4000)
GMod version 2024.07.16, branch: x86-64, multicore: 1
Linux 64bit
 ```

**Additional context**
Seems like undesirable behavior.

**Comment by TeddiO** [comment]
This has been discussed here partially: https://github.com/BB-Games/gamemode-issues-requests/issues/66

You're right in that it's undesirable behaviour, though at the time we hadn't really settled on a decision. I suppose we'll likely do what @killermon suggested which is to expose something internally so things like refunds wouldn't count.
