### ISSUE TITLE
Add Ahop zones to surf_healthy S3/starfruit

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#7]
**Is your feature request related to a problem? Please describe.**
I can't bhop for shite and I'd like some naisu ahop zones added to the platforms on surf_healthy S3/Starfruit

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Delete all bhop forever

**Additional context**
Add zones on the startfruit platforms pictured here: https://i.imgur.com/DtFC5zN.png

**Comment by TeddiO** [comment]
Added
