### ISSUE TITLE
Hide /tryplat messages

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#70]
**Describe the bug:**
A /tryplat message keeps appearing while having chat ticker disabled & after redeeming my week of platinum. Please classify this message as a ticker or hide after redemption:

``` During the anniversary you can try Platinum for free! Type /tryplat now! ```

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.07.30, branch: x86-64, multicore: 1
Linux 64bit
```

**Comment by TeddiO** [comment]
I'm adding a change that will suppress / hide it for Platinum players. Later on in the week I'll see how much effort it is to identify a completed trial and to suppress the message for those as well.
