### ISSUE TITLE
Player Models and Chat Text Color not Being Saved With an Active Trial of Platinum

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#71]
**Describe the bug**
If you change your active player model to a player model exclusive to Platinum members and change your chat text color to any non-default color with an account that has an active Platinum trial membership, these changes will not be saved after a server ``changelevel`` or when re-joining the server.

**Corresponding lua error**
_No Corresponding Lua Error with this Bug._

**Steps to reproduce the behavior:**
    1. Join a BB Surf Server on an Account that does NOT have an active Platinum membership 
    2. Active a free trial of Platinum during the anniversary with the ``/tryplat`` command
    3. Change your player model in the F1 menu (or through convars) to a model that is exclusive to Platinum members
    4. Set your Chat Text Color to a color of your choosing
    5. ``retry`` the server in console (or await a map vote) and observe as your changes were not saved upon re-entering the server.

**Screenshots**

**System Information:**
```Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:05:22 Jul 22 2024 (9379) (4000)
GMod version 2024.08.05, branch: x86-64, multicore: 1
Windows 64bit```

**Additional context**
It seems this issue only applies to changes to Platinum exclusive player models and your chat text color. Other Platinum features seem to work as intended.

This issue is also persistent when changing your player model through BB Platinum convars.

**Comment by TeddiO** [comment]
This will be resolved once the issue is closed and about 30-40 minutes has passed.
