### ISSUE TITLE
Option to hide hovering name & rank

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#76]
**Why you would like to see this resolved, what does it enhance / bring to the table?**
Prevents any chance of obscene language appearing on screen & makes me confident that the content I release won't lead to somebody who didn't consent to being in it getting harassed. Settings exist to hide all of the other identifying information from appearing during game play & this is the only one missing.

**Additional context**
Part of my project includes a time lapse where playermodels will cross my crosshair every few seconds. Even though the hovering feature doesn't work as intended with my platform, I think names will still appear in a few frames & I can't be certain I will be able to edit each of those frames out of hours of recording.

**Comment by TeddiO** [comment]
Added `surf_enable_targetid` which defaults to `1`. Setting to `0` will disable the target ID (internal name for name / rank info)
