### ISSUE TITLE
Receiving DNF messages from recipients outside the group

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#77]
**Describe the bug**
DNF messages appear while a race is active regardless of the recipient interacting with the invite.

**How to reproduce the issue**
1. Invite someone to your group. Do not accept the invite.
2. Start the race.
3. Whenever the recipient resets, you will receive a chatbox message.

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Linux 64bit
```

**Additional context**
Kinda weird behavior to be able to monitor when someone is resetting.

**Comment by TeddiO** [comment]
To clarify, when you say the recipient, you mean the person that has been invited?

**Comment by Sod-ers** [comment]
Correct, the person that received my /invite.

**Comment by TeddiO** [comment]
This should be resolved when the servers next changelevel. Please report back if that's not the case.
