### ISSUE TITLE
Add Ahop zones to surf_healthy S9/cucumber

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#8]
**Is your feature request related to a problem? Please describe.**
I can't bhop for shite and I'd like a naisu ahop zone added to the ramp/platform on surf_healthy S9/Cucumber

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Delete all bhop forever

**Additional context**
Add zone onto this ramp/platform in Cucumber: https://i.imgur.com/MNQCaU4.png

**Comment by TeddiO** [comment]
Added
