### ISSUE TITLE
Add "Cigar" cosmetic to The Bazaar

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#85]
**Why you would like to see this resolved, what does it enhance / bring to the table?**
Collectors are eager to have this item & I don't know of a way to obtain it other than older crates.

**Comment by TeddiO** [comment]
The Cigar isn't obtainable at all, it's an internal item that never functioned (essentially it's missing its smoke particle). It's unlikely it'll be made for the foreseeable future.
