### ISSUE TITLE
Holiday restricted items may still appear in headgear crafting rewards

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#90]
**Describe the bug:**
An item I recognize as holiday restricted was crafted, please validate. ```Towering Patch``` is from Halloween. ```Particulate Protector``` was also crafted, it's the reward for the achievement "I Survived 2021". Not sure if you intend for those achievement items to be included in crafting.

**Screenshots:**
![1](https://github.com/user-attachments/assets/ac8f082e-1c07-4eeb-ab8b-10b031f9f1f1)

**System information:**

```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:03:26 Jul 22 2024 (9379) (4000)
GMod version 2024.09.09, branch: x86-64, multicore: 1
Linux 64bit
```

**Additional context:**
You may want to refund or credit astra's infinity essences. They asked about crafting advice & I advised them about holiday items being removed. I began to test the issue earlier myself but didn't get to extensively.

When an update is made to this issue, I will test the issue myself by crafting a bunch of headgears. If cosmetic names I suspect to be holiday restricted appear, I can provide those.

**Comment by TeddiO** [comment]
I've gone through and changed a number of global craft flags,  including some holiday items and and achievement items. It'll take a changelevel for each server to take effect.
