### ISSUE TITLE
Option to disable web page feature in menu

### ISSUE THREAD

**Issue by Sod-ers** [BB-Games/gamemode-issues-requests#91]
**Is your feature request related to a problem? Please describe.**
Occasional crashes persist on Linux, opening the menu causes the crash. The crash occurs before I can see the web page, potentially during the process of loading it.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
May fix my client crashes & could help performance for users on older hardware.

**Comment by TeddiO** [comment]
A while after this issue is closed, the convar `bb_menu_disable_help` should be available. When set to 1, it disables the HTML element of the F1 page and displays an alternate message instead.
